require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.treesitter"
spec "user.telescope"
spec "user.nvim-tree"
spec "user.nvim-tmux-navigation"

require "user.lazy"
